metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.1.210, mac: '00:23:24:d1:f3:f0', disk: sda, network_interface: enp0s4}
        metal1: {ansible_host: 192.168.1.211, mac: '00:23:24:d1:f4:d6', disk: sda, network_interface: enp0s4}
        metal2: {ansible_host: 192.168.1.212, mac: '00:23:24:e7:04:60', disk: sda, network_interface: enp0s4}
    workers:
      hosts:
        metal3: {ansible_host: 192.168.1.213, mac: '00:23:24:d1:f5:69', disk: sda, network_interface: enp0s4}
